# @host = "http://localhost:258"
@hosta = "http://localhost:958"
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6ImV1cm85NTgiLCJpYXQiOjE3NTU4ODQyNDMsImV4cCI6MTc1NTg5ODY0M30.aRgOvqB9JWU2JzDOiMOOQClF-0THJ1l-niCtmsWD62w

###

# @name Authentication
POST /authorize
Host: localhost:958
Content-Type: application/json

{
	"password": "euro958"
}

###

# @name common_getIPLocal
GET /common/getIPLocal
Host: localhost:258

###

# @name database_query
POST http://localhost:958/database/query
Authorization: {{token}}
Content-Type: application/json

{
	"database": "calendar",
	"sql": "SELECT * FROM calendar WHERE 1 = 1"
}

###

# @name file_list
GET /file/list?folder=C:\Projects\MtNodeJS
Host: localhost:958

###

# @name file_read
GET /file/read?file=C:\Projects\MtNodeJS\package.json
Host: localhost:958

###

# @name file_write
POST /file/write?folder=C:\Users\Windows\Downloads\test\wat
Host: localhost:258
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="music_202406262017.csv"
Content-Type: text/csv

< C:\Users\Windows\Downloads\draft\music_202406262017.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name file_register
POST /file/register
Host: localhost:958
Authorization: {{token}}
Content-Type: application/json

{
	"folder": "C:/Massan/Walpapers"
}

###

# @name file_static
GET /file/static?folder=C:\Massan\Walpapers&file=30004.jpg
Host: localhost:958

###

# @name music_init
GET /music/init HTTP/1.1
Host: localhost:258

###

# @name music_getListMusic
POST /music/getListMusic HTTP/1.1
Host: localhost:958
Content-Type: application/json

###
